"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ProductService_1 = require("./ProductService");
var product_1 = require("./product");
var _productService = new ProductService_1.ProductService();
var result;
result = _productService.getById(2);
var p = new product_1.product();
p.name = "Ipone 6";
p.price = 4000;
p.category = "telefon";
// _productService.saveProduct(p);
_productService.deletProduct(result);
result = _productService.getProducts();
console.log(result);
